apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiger-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tiger
  template:
    metadata:
      labels:
        app: tiger
    spec:
      serviceAccountName: tiger-operator
      containers:
      - name: tiger-container
        image: giacomo12305/tiger-app:latest
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
