apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - security/role.yaml           # <-- Percorso aggiornato
  - security/role-binding.yaml   # <-- Percorso aggiornato

images:
  - name: giacomo12305/tiger-app
    newTag: '4'
